[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "discord_bot"
version = "0.1.0"
description = "This is a simple Discord bot."
license = "MIT"
